### ISSUE TITLE
OSError: [Errno -9996] Invalid input device

### ISSUE THREAD

**Issue by basnijholt** [home-assistant/dude#10]
I am running on a Pi 4 with Home Assistant 0.102.3 using Hass.io.

I have the Almond add-on working, however, when starting the Ada add-on I get the following traceback:
```python
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 924
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 924
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.front
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround40
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround41
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround50
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround51
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm_hw.c:1822:(_snd_pcm_hw_open) Invalid value for card
ALSA lib pcm_hw.c:1822:(_snd_pcm_hw_open) Invalid value for card
ALSA lib pcm_hw.c:1822:(_snd_pcm_hw_open) Invalid value for card
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/src/ada/ada/__main__.py", line 47, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/src/ada/ada/__main__.py", line 42, in main
    ada.run()
  File "/usr/src/ada/ada/__init__.py", line 31, in run
    self.microphone.start()
  File "/usr/src/ada/ada/microphone.py", line 49, in start
    frames_per_buffer=self.frame_length,
  File "/usr/local/lib/python3.7/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9996] Invalid input device (no default output device)
```

As I [wrote on the forum](https://community.home-assistant.io/t/replacing-alexa-or-google-home-by-almond-and-ada/152666/7?u=basnijholt), I am not sure whether this is expected as I do not have a microphone or speaker connected.

These are my audio settings:
![image](https://user-images.githubusercontent.com/6897215/70181884-08d84580-16e3-11ea-90d5-3e44f8391097.png)
Even though I have no output device, still something is selected.

**Comment by pvizeli** [comment]
Yeah, a voice assistant without a microphone will not work 🤔

**Comment by basnijholt** [comment]
Ah, I had the impression that when I used voice input with Almond, like
![image](https://user-images.githubusercontent.com/6897215/70182265-ca8f5600-16e3-11ea-9a70-0b687844ddc0.png)
That I used Ada for this, but that must be something else then.

**Comment by basnijholt** [comment]
Would it be possible to connect Ada to a remote stream, like with [Rhasspy](https://rhasspy.readthedocs.io/en/latest/audio-input/#mqtthermes)? 
Should I open a separate issue for this? Or is it better to keep the discussion [here](https://community.home-assistant.io/t/replacing-alexa-or-google-home-by-almond-and-ada/152666/6)?

**Comment by pvizeli** [comment]
This one use browser STT (chrome -> google) and send it to our conversation platform.

Ada is a local Voice Assistant they handle hotword and use the platforms/integration of Home Assistant to handle the functionality of a Voice Assistant.

The code is now open for the community to extend it with more functionality. If there is a good use case for hermes, feel free to implement this functionality.

**Comment by basnijholt** [comment]
Thanks for the quick answers!

> If there is a good use case for hermes, feel free to implement this functionality.

When I get my microphone, I'll start testing and might submit a PR if I decide that the functionality is useful for me 👍
